version: "3"
services:
  influx_db:
    image: influxdb:2.7
    mem_limit: 512m
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_database/influxdb:/var/lib/influxdb2
      - ./influxconfigs/influxdb:/etc/influxdb2
    environment:
    ## DO NOT USE THIS IN PRODUCTION
    ## THIS IS FOR INTEGRATION TESTING ONLY!!!!!
      - INFLUXDB_DB=test_db
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123!
      - DOCKER_INFLUXDB_INIT_ORG=test_org
      - DOCKER_INFLUXDB_INIT_BUCKET=test_bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=0123456789
  influxdb_rs:
    build:
      context: ./
      dockerfile: Dockerfile 
    