version: "3"
services:
  influx_db:
    image: influxdb:2.3
    mem_limit: 512m
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb_database/influxdb:/var/lib/influxdb2
      - ./influxconfigs/influxdb:/etc/influxdb2
    environment:
      - INFLUXDB_DB=test_db
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
  influxdb_rs:
    build:
      context: ./
      dockerfile: Dockerfile 
    